[build]
builder = "NIXPACKS"

[build.nixpacksPlan.phases.install]
cmds = [
  "pip install -r utim_cli/server/requirements.txt"
]

[deploy]
startCommand = "uvicorn utim_cli.server.router:app --host 0.0.0.0 --port $PORT --workers 1"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
